export const products = [
  {
    id: "1",
    name: "Vietnamese Straight Wig",
    category: "wigs",
    type: "vietnamese",
    price: 170000,
    texture: "curly",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "2",
    name: "Vietnamese Straight Wig",
    category: "wigs",
    type: "vietnamese",
    price: 180000,
    texture: "straight",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "3",
    name: "Vietnamese Straight Wig",
    category: "wigs",
    type: "vietnamese",
    price: 280000,
    texture: "wavy",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "4",
    name: "Vietnamese Straight Wig",
    category: "wigs",
    type: "vietnamese",
    price: 180000,
    texture: "straight",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "5",
    name: "Vietnamese Straight Wig",
    category: "wigs",
    type: "vietnamese",
    price: 170000,
    texture: "curly",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "6",
    name: "Vietnamese Straight Wig",
    category: "wigs",
    type: "vietnamese",
    price: 280000,
    texture: "wavy",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "7",
    name: "Vietnamese Straight Wig",
    category: "wigs",
    type: "vietnamese",
    price: 180000,
    texture: "straight",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "8",
    name: "Vietnamese Straight Wig",
    category: "wigs",
    type: "vietnamese",
    price: 180000,
    texture: "straight",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "9",
    name: "Bob Wig",
    category: "wigs",
    type: "bob",
    price: 70000,
    texture: "straight",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "10",
    name: "Bob Wig",
    category: "wigs",
    type: "bob",
    price: 65000,
    texture: "wavy",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "11",
    name: "Bob Wig",
    category: "wigs",
    type: "bob",
    price: 70000,
    texture: "straight",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "12",
    name: "Bob Wig",
    category: "wigs",
    type: "bob",
    price: 90000,
    texture: "curly",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "13",
    name: "Bob Wig Bundle",
    category: "bundles",
    price: 90000,
    texture: "straight",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "14",
    name: "Vietnamese Bundle",
    category: "bundles",
    price: 90000,
    texture: "wavy",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "15",
    name: "Bundle",
    category: "bundles",
    price: 90000,
    texture: "curly",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
  {
    id: "16",
    name: "Bundle",
    category: "bundles",
    price: 90000,
    texture: "curly",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    length: [],
    images: [
      "bg-amber-200",
      "bg-teal-200",
      "bg-fuchsia-200",
      "bg-red-200",
      "bg-stone-200",
      "bg-blue-200",
    ],
  },
];
